# Generated by Django 3.2.17 on 2023-02-04 15:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20230126_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='featured_image'),
        ),
    ]
