# Generated by Django 3.2.17 on 2023-02-05 03:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='excerpt',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
