# Generated by Django 3.2.17 on 2023-02-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20230213_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
