# Generated by Django 3.2.17 on 2023-05-23 15:08

import book.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20230205_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(validators=[book.validators.validate_date]),
        ),
    ]
